#!/bin/bash
while [ 1 -lt 4 ]
do
        curl -I -k https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        curl -I -k  https://load.ms.local
        sleep 0.5
done
