apiVersion: v1
kind: Service
metadata:
  name: apache-service
  annotations:
    service.citrix.com/frontend-ip: 10.0.1.17
    service.citrix.com/service-type-0: 'HTTP'
    service.citrix.com/lbvserver: '{"80-tcp":{"lbmethod":"ROUNROBIN"}}'
    service.citrix.com/servicegroup: '{"80-tcp":{"usip":"no"}}'
    service.citrix.com/ssl-termination: edge
    service.citrix.com/monitor: '{"80-tcp":{"type":"http"}}'
    service.citrix.com/frontend-httpprofile: '{"dropinvalreqs":"enabled", "websocket" : "enabled"}'
    service.citrix.com/backend-httpprofile: '{"dropinvalreqs":"enabled", "websocket" : "enabled"}'
    service.citrix.com/frontend-tcpprofile: '{"ws":"enabled", "sack" : "enabled"}'
    service.citrix.com/backend-tcpprofile: '{"ws":"enabled", "sack" : "enabled"}'
spec:
  type: LoadBalancer
  selector:
    app: apache
  ports:
  - port: 80
    targetPort: 80
    name: http
