apiVersion: v1
kind: Pod
metadata:
  name: exporter
  labels:
    app: exporter
spec:
  containers:
    - name: exporter
      image: quay.io/citrix/citrix-adc-metrics-exporter:1.4.9
      args:
        - "--target-nsip=10.0.70.131"
        - "--port=8888"
      imagePullPolicy: Always
      volumeMounts:
      - name: nslogin
        mountPath: "/mnt/nslogin"
        readOnly: true
      securityContext:
        readOnlyRootFilesystem: true
  volumes:
  - name: nslogin
    secret:
      secretName: nsloginexp
---

kind: Service
apiVersion: v1
metadata:
  name: exporter-vpx-service
  labels:
    service-type: citrix-adc-monitor
spec:
  type: NodePort
  selector:
    app: exporter
  ports:
    - name: exporter-port
      port: 8888
